site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.tabs.expand
    - navigation.tabs.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - Home: index.md
  - Mycode:
      - C++: coding/file1forcoding.md
  - About:
      - Current Projects: about/projects.md
      - About Me: about/about.md
      - Childhood: about/childhood.md
  - Tags: tags.md
  - Blog: 
    - blog/index.md
